sugarcube-2:
  macros:
    eggOne:
      name: eggOne
    colOne:
      name: colOne
    growUp:
      name: growUp
    hatchDragon:
      name: hatchDragon
    wanderDragon:
      name: wanderDragon
    dragonMaker:
      name: dragonMaker
    hatchMaker:
      name: hatchMaker
    eggMaker:
      name: eggMaker
    updateBar:
      name: updateBar
    endDay:
      name: endDay
    numberinput:
      name: numberinput
    dragonWanderer:
      name: dragonWanderer
    updateHome:
      name: updateHome
    addRut:
      name: addRut
    addSett:
      name: addSett
    buildQueue:
      name: buildQueue
    countWorkers:
      name: countWorkers
    addHollow:
      name: addHollow
    errorPopup:
      name: errorPopup
