sugarcube-2:
  macros:
    eggOne:
      name: eggOne
    colOne:
      name: colOne
    growUp:
      name: growUp
    hatchDragon:
      name: hatchDragon
    wanderDragon:
      name: wanderDragon
    dragonMaker:
      name: dragonMaker
    hatchMaker:
      name: hatchMaker
    eggMaker:
      name: eggMaker
    updateBar:
      name: updateBar
    endDay:
      name: endDay
    numberinput:
      name: numberinput
    dragonWanderer:
      name: dragonWanderer
    updateHome:
      name: updateHome
    addRut:
      name: addRut
    addSett:
      name: addSett
    buildQueue:
      name: buildQueue
    countWorkers:
      name: countWorkers
    addHollow:
      name: addHollow
    errorPopup:
      name: errorPopup
    updateDefense:
      name: updateDefense
    addResource:
      name: addResource
    plural:
      name: plural
    buildTimeSanityCheck:
      name: buildTimeSanityCheck
    timeKeeper:
      name: timeKeeper
    eggUpdates:
      name: eggUpdates
    hatchlingUpdates:
      name: hatchlingUpdates
    dailyPlayerReset:
      name: dailyPlayerReset
    feedPlayer:
      name: feedPlayer
    dragonJobs:
      name: dragonJobs
    dragonsJobs:
      name: dragonsJobs
    shelterMoving:
      name: shelterMoving
    feedHatchlings:
      name: feedHatchlings
    feedDragons:
      name: feedDragons
    capResources:
      name: capResources
    voluntaryDeparture:
      name: voluntaryDeparture
    exileDragons:
      name: exileDragons
    builderRestDisplay:
      name: builderRestDisplay
    resetDefense:
      name: resetDefense
    relationshipEventTrigger:
      name: relationshipEventTrigger
